# Cloudflare Pages configuration for Destiny Armor Picker
# wrangler v4.37.1+

name = "destiny-armor-picker"
compatibility_date = "2024-01-15"

# Pages configuration
pages_build_output_dir = ".next"

# Compatibility flags for Next.js (must be array format)
compatibility_flags = ["nodejs_compat"]

# Environment variables (set these in Cloudflare dashboard)
[vars]
# These will be overridden by environment variables in Cloudflare dashboard
NODE_ENV = "production"

# Observability settings
[observability]
enabled = true

[observability.logs]
enabled = false

# Disable telemetry for cleaner builds
send_metrics = false