# Cloudflare Pages configuration for Destiny Armor Picker
# wrangler v3.88.0+

name = "destiny-armor-picker"
compatibility_date = "2024-01-15"

# Pages configuration
[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "directory"
dir = ".next"

# Environment variables (set these in Cloudflare dashboard)
[vars]
# These will be overridden by environment variables in Cloudflare dashboard
NODE_ENV = "production"

# Observability settings
[observability]
enabled = true

[observability.logs]
enabled = false

# Compatibility flags for Next.js
[compatibility_flags]
nodejs_compat = true

# Functions configuration for API routes
[[pages_build_output_dir]]